FROM golang:1.23-alpine

ENV GOTOOLCHAIN=local
RUN go install github.com/air-verse/air@v1.61.1

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
